### PR TITLE
Add SF UI Text font

### PR DESCRIPTION
**Pull request by mnquintana**
Refs https://github.com/atom/one-dark-ui/pull/81

/cc @simurai

### CODE REVIEW

**Comment by simurai** [comment]
I think it would need some more tweaks. It seems that the baseline of the SF font is positioned a bit higher in some cases, e.g. status bar:

sf-font

For the One themes it's less noticeable, maybe because they don't use a fixed line-height and have a little more padding. It also depends on the font-size.

I would say..

1. Either try to adjust the positioning everywhere.
2. Or keep using `Lucida Grande`? I think it looks pretty sharp when used with the current `11px` font-size.

**Comment by thomasjo** [comment]
> I would say..
> 
>  1. Either try to adjust the positioning everywhere.
>  2. Or keep using Lucida Grande? I think it looks pretty sharp when used with the current 11px font-size.

I say we attempt approach 1, because we should not be dependent upon fixed line heights anywhere in the UI in my opinion. We need to be more flexible than that. Since SF is the new default in El Capitan I really think we should work towards using that to prevent Atom from looking "out of place" once El Cap lands.

**Comment by mnquintana** [comment]
> I say we attempt approach 1, because we should not be dependent upon fixed line heights anywhere in the UI in my opinion. We need to be more flexible than that. Since SF is the new default in El Capitan I really think we should work towards using that to prevent Atom from looking "out of place" once El Cap lands.

Agreed. I'll take a look at fixing this soon.

**Comment by simurai** [comment]
@mnquintana Ok, let me know if you get stuck. It might just be a few tweaks. Or it could be a :rabbit: hole where it needs changes everywhere.

**Comment by lee-dohm** [comment]
@mnquintana Is this PR still necessary?

**Comment by simurai** [comment]
Changed this PR to the default fonts.

Also the "jumping" seems to be fixed:

font

So I think this is good to go.

**Pull request merged**
