### PR TITLE
Fixed inline-code rendering issue.

### PR DESCRIPTION
**Pull request by richerlariviere**
Fix of issue #8575 (https://github.com/atom/atom/issues/8575)

### CODE REVIEW

**Comment by simurai** [comment]
It seems the issue only happens in Markdown Preview (because the background is white).

How about scoping it to only `.markdown-preview` like:

```css
.markdown-preview code {
  text-shadow: none;
}
```

**Comment by richerlariviere** [comment]
You're right about it. I will close this pull request.

**Comment by richerlariviere** [comment]
I looked at the code of other atom themes and I saw a `markdown-preview.less` file. What do you think about that?

**Comment by simurai** [comment]
> I looked at other atom themes and I saw a `markdown-preview.less` file. What do you think about that?

Ya, that would be a cleaner separation. Although an extra file for just a single rule might be a bit excessive?

I think keeping it in `text.less` for now is fine. And then in case there are more overriding needed, it could be split up.

Anyways, thanks for fixing this. :+1:

**Pull request merged**
